[package]
name = "mtgoupdater"
version.workspace = true
authors.workspace = true
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["mtgo"]
description = "Library for interoperating with MTGO Collection manager's C++ and Go code"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "0.4.31"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
zip = "0.6.6"
mtgoparser-rs = { path = "../mtgoparser-rs", version = "*" }


[dev-dependencies]
pretty_assertions.workspace = true
temp-dir.workspace = true

[lints]
workspace = true
