name: benchmarks

on:
  workflow_dispatch:

env:
  VERBOSE: 1

jobs:
  Benchmark-mtgoparser:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc-13
            generator: "Ninja Multi-Config"
            enable_ipo: On
            packaging_maintainer_mode: OFF
            build_shared: OFF

          - os: macos-12
            compiler: llvm-15.0.3
            generator: "Ninja Multi-Config"
            enable_ipo: Off
            packaging_maintainer_mode: OFF
            build_shared: OFF

          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            enable_ipo: On


    name: MTGO-Parser-benchmark
    steps:
      - uses: actions/checkout@v3
      - uses: aminya/setup-cpp@v1
        with:
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📝 Build & Run benchmarks - 🐧🍎💻
        run: |
          task mtgoparser:build-for-integration
          task mtgoparser:benchmark

  Benchmark-mtgogetter:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022
    name: MTGO-Getter-benchmark
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: 📝 Build & Run benchmarks - 🐧🍎💻
        if: runner.os != 'Windows'
        run: |
          echo placeholder
        #  task mtgogetter:bench


  # Benchmark-mtgoupdater:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - os: ubuntu-22.04
  #         - os: macos-12
  #         - os: windows-2022
  #   name: MTGO-Updater-benchmark
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: moonrepo/setup-rust@v1

  #     - name: 📝 Build & Run benchmarks - 🐧🍎💻
  #       run: |
  #         echo placeholder
  #       #  task mtgoupdater:benchmark