name: mtgoupdater-ci

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
      - master
    branches:
      - develop
      - master

env:
  VERBOSE: 1

jobs:
    # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      mtgoupdater: ${{ steps.filter.outputs.mtgoupdater }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          mtgoupdater:
            - 'mtgoupdater/**'


  test-ubuntu:
    # Only run if there's changes to the Rust code (in /mtgoupdater)
    needs: changes
    if: ${{ needs.changes.outputs.mtgoupdater == 'true' }}
    runs-on: ubuntu-latest

    name: Build & Test Ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: check
        working-directory: ./mtgoupdater
        run: |
          cargo check --verbose
      - name: test
        working-directory: ./mtgoupdater
        run: |
          cargo test --verbose -- --nocapture