name: mtgogetter-ci

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
      - master
    branches:
      - develop
      - master

env:
  VERBOSE: 1

jobs:
    # JOB to run change detection
  changes:
    name: 🔎 Detect Code Changes before running CI Jobs 🔬
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      mtgogetter: ${{ steps.filter.outputs.mtgogetter }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          mtgogetter:
            - 'mtgogetter/**'



  build-Go:
    # Only run if there's changes to the Go code (in /mtgogetter)
    needs: changes
    if: ${{ needs.changes.outputs.mtgogetter == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go 🛠️ Toolchain
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ⚒️ MTGO Getter 🐹
      run: task mtgogetter:build

    - name: Test 📝 MTGO Getter 🐹
      run: task mtgogetter:test
