name: mtgogetter-ci

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
      - main
    branches:
      - main
      - develop

jobs:
    # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      mtgogetter: ${{ steps.filter.outputs.mtgogetter }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          mtgogetter:
            - 'mtgogetter/**'

  build:
    # Only run if there's changes to the Go code (in /mtgogetter)
    needs: changes
    if: ${{ needs.changes.outputs.mtgogetter == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -C mtgogetter -v

    # TODO: Implement tests
    #- name: Test
    #  run: go test -v ./...
